version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nodeDefault.conf:/etc/nginx/conf.d/default.conf

  nest:
    build: .
    ports:
      - '3000:3000'
    enviroment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LAUNCH_ENV=docker-compose
