version: '3.9'
services:
  nginx:
    image: nginx:latest
    networks:
      - safe_pill
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  nest:
    build: .
    networks:
      - safe_pill
    ports:
      - '3000:3000'

  # backend:
  # build: ../capstone
  # context: backend
  # ports:
  # - '8080:8080'

networks:
  safe_pill:
    driver: bridge
